config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'board_games#index'

  resources :board_games
   
  namespace :admin do
    resources :users, only: [:index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board_game.rb
class BoardGame < ApplicationRecord
  has_many :board_game_collections
  has_many :users, through: :board_game_collections

  validates :name, presence: true
  validates :name, uniqueness: true

  validates :publisher, presence: true

  validates :min_players, numericality: { greater_than: 0 }
  validates :max_players, numericality: { greater_than: 0 }
end

app/models/board_game_collection.rb
class BoardGameCollection < ApplicationRecord
  belongs_to :user
  belongs_to :board_game
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :board_game_collections
  has_many :board_games, through: :board_game_collections

  validates :email, uniqueness: true
  validates :role, inclusion: { in: ['user', 'admin'] }

  def is_admin?
    role == 'admin'
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authorize_admin!

  def index
    @users = User.all
  end

  private

  def authorize_admin!
    # binding.pry
    if current_user.role == "admin"
    else
      flash[:notice] = 'You are not authorized.'
      redirect_to :root
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }

  private

  def authorize_admin!
    # binding.pry
    if current_user.nil? or !current_user.is_admin?
      flash[:notice] = 'You are not authorized to view this content.'
      redirect_to :root
    end
  end

end

app/controllers/board_games_controller.rb
class BoardGamesController < ApplicationController
  before_action :set_board_game,
    only: [:show, :edit, :update, :destroy]

  def index
    @board_games = BoardGame.all
  end

  def show
  end

  def new
    @board_game = BoardGame.new
  end

  def edit
  end

  def create
    @board_game = BoardGame.new(board_game_params)
    if @board_game.save
      redirect_to board_games_path,
        notice: 'Board game was successfully created.'
    else
      render :new
    end
  end

  def update
    if @board_game.update(board_game_params)
      redirect_to @board_game,
        notice: 'Board game was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @board_game.destroy
    redirect_to board_games_url,
      notice: 'Board game was successfully destroyed.'
  end

  private
    def set_board_game
      @board_game = BoardGame.find(params[:id])
    end

    def board_game_params
      params.require(:board_game).
        permit(
          :name,
          :publisher,
          :description,
          :release_date,
          :min_players,
          :max_players
        )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_games_helper.rb
module BoardGamesHelper
end

app/views/admin/users/index.html.erb
<% @users.each do |user| %>
  <h4><%= user.email %></h4>
<% end %>

<h4> not authorized </h4>

app/views/board_games/_form.html.haml
= form_for @board_game, html: { role: :form } do |f|
  - if @board_game.errors.any?
    #error_explanation
      %h2= "#{pluralize(@board_game.errors.count, "error")} prohibited this board_game from being saved:"
      %ul
        - @board_game.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"

  .form-group
    = f.label :publisher
    = f.text_field :publisher, class: "form-control"

  .form-group
    = f.label :description
    = f.text_area :description, class: "form-control"

  .form-group
    = f.label :min_players
    = f.number_field :min_players, min: 1, class: "form-control"

  .form-group
    = f.label :max_players
    = f.number_field :max_players, min: 1, class: "form-control"

  .form-group
    = f.label :release_date
    = f.date_field :release_date, class: "form-control"

  .actions
    = f.submit nil, class: "btn btn-default"

app/views/board_games/edit.html.haml
%h1 Editing Board Game

= render 'form'

= link_to 'Show', @board_game
\|
= link_to 'Back', board_games_path

app/views/board_games/index.html.haml
%h1 Listing Board Games

%table.table.table-hover
  %tr
    %th Name
    %th Publisher
    %th Release Date
    %th
    %th
    %th

  - @board_games.each do |board_game|
    %tr
      %td= link_to board_game.name, board_game
      %td= board_game.publisher
      %td= board_game.release_date
      %td= link_to 'Show', board_game
      %td= link_to 'Edit', edit_board_game_path(board_game)
      %td= link_to 'Destroy', board_game, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Board game', new_board_game_path

app/views/board_games/new.html.haml
%h1 New Board Game

= render 'form'

= link_to 'Back', board_games_path

app/views/board_games/show.html.haml
%h1= @board_game.name

%div
  %b Publisher
  = @board_game.publisher

%div
  %b Descritption
  = @board_game.description

%div
  %b Release Date
  = @board_game.release_date

%div
  %b Players
  = "#{@board_game.min_players} to #{@board_game.max_players}"

= link_to 'Edit', edit_board_game_path(@board_game)
\|
= link_to 'Back', board_games_path

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="flash flash-<%= type %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameCollector</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <%= render "layouts/flash" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>